""" Namespace for standard list of files to repatriate. """

POSCAR  = "POSCAR"
""" Name of the input structure file. """
KPOINTS = "KPOINTS"
""" Name of the kpoints file. """
INCAR   = "INCAR"
""" Name of the input parameters file. """
POTCAR  = "POTCAR"
""" Name of the pseudopotential file. """
WAVECAR = "WAVECAR"
""" Name of the wavefunction file. """
CONTCAR = "CONTCAR"
""" Name of the output structure file. """
CHGCAR  = "CHGCAR"
""" Name of the output charge file. """
OSZICAR = "OSZICAR"
""" Name of the energy minimization file. """
STDOUT  = "stdout"
""" Name of the standard output file. """
STDERR  = "stderr"
""" Name of the standard error file. """
EIGENVALUES = "EIGENVAL"
""" Name of the file with eigenvalues. """
OUTCAR = "OUTCAR"
""" Name of the output file. """
WAVEDER = "WAVEDER"
""" Name of GW-required file. """
TMPCAR = 'TMPCAR'
""" Name of temporary wavefunctions file. """
POT    = 'POT'
""" Name of the local potential file. """
