#! /bin/tcsh
#
#PBS -l mppwidth=16
#PBS -l walltime=00:30:0
#PBS -q interactive
#PBS -m n 
#PBS -e err
#PBS -o out
module load fftw parpack pgi


cd  $PBS_O_WORKDIR/calc
rm sendme.*

cp ../../../debug_mpi/darwin/bandgap_opt .
cp ../input.xml .
pwd
aprun -n 16  ./bandgap_opt

exit
