#! /bin/tcsh
#
#PBS -l mppwidth=8
#PBS -l walltime=00:30:0
#PBS -q interactive
#PBS -m n 
#PBS -e err
#PBS -o out
module load fftw parpack pgi


cd  $PBS_O_WORKDIR/calc
rm sendme.*

cp ../../../build_mpi/darwin/bandgap_opt .
cp ../input.xml .
pwd
aprun -n 8  ./bandgap_opt 

exit
