#! /bin/tcsh
#
#PBS -l mppwidth=7
#PBS -l walltime=00:10:0
#PBS -q debug
#PBS -m n 
#PBS -e err
#PBS -o out
module load openmpi fftw arpack pgi


cd  $PBS_O_WORKDIR/calc
rm sendme.*

cp ../../../../build/darwin/bandgap_opt .
cp ../input.xml .
echo "mpirun -np $PBS_NPROCS  --hostfile $PBS_NODEFILE  ./bandgap_opt"

aprun -n $PBS_NPROCS   ./bandgap_opt 

exit
